<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.506">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sangho Lee">
<meta name="dcterms.date" content="2024-05-28">

<title>hw4_questions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="hw4_questions_files/libs/clipboard/clipboard.min.js"></script>
<script src="hw4_questions_files/libs/quarto-html/quarto.js"></script>
<script src="hw4_questions_files/libs/quarto-html/popper.min.js"></script>
<script src="hw4_questions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="hw4_questions_files/libs/quarto-html/anchor.min.js"></script>
<link href="hw4_questions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="hw4_questions_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="hw4_questions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="hw4_questions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="hw4_questions_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sangho Lee </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 28, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<p>This post implements a few measure of variable importance, interpreted as a key drivers analysis, for certain aspects of a payment card on customer satisfaction with that payment card.</p>
<section id="data" class="level3">
<h3 class="anchored" data-anchor-id="data">Data</h3>
<section id="i-will-start-by-calling-the-necessary-packages-in-both-r-and-python-to-facilitate-data-handling-and-analysis." class="level5">
<h5 class="anchored" data-anchor-id="i-will-start-by-calling-the-necessary-packages-in-both-r-and-python-to-facilitate-data-handling-and-analysis.">I will start by calling the necessary packages in both R and Python to facilitate data handling and analysis.</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pyrsm <span class="im">as</span> rsm</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">"data_for_drivers_analysis.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(scales)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(reticulate)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(relaimpo)</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caret)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stats)</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gt)</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(iml)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"data_for_drivers_analysis.csv"</span>)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>df <span class="sc">%&gt;%</span> </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>(<span class="dv">10</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 6%">
<col style="width: 4%">
<col style="width: 14%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 8%">
<col style="width: 5%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 8%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">brand</th>
<th style="text-align: right;">id</th>
<th style="text-align: right;">satisfaction</th>
<th style="text-align: right;">trust</th>
<th style="text-align: right;">build</th>
<th style="text-align: right;">differs</th>
<th style="text-align: right;">easy</th>
<th style="text-align: right;">appealing</th>
<th style="text-align: right;">rewarding</th>
<th style="text-align: right;">popular</th>
<th style="text-align: right;">service</th>
<th style="text-align: right;">impact</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">98</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">179</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">197</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">317</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">356</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">395</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">586</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">596</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">978</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">987</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="data-explanation" class="level3">
<h3 class="anchored" data-anchor-id="data-explanation">Data Explanation</h3>
<ul>
<li>brand: Indicates the brand of the payment card. Coded numerically.</li>
<li>id: A unique identifier for each record in the dataset.</li>
<li>satisfaction: The overall customer satisfaction with the payment card, typically on a scale (e.g., 1 to 5).</li>
<li>trust: Measures the level of trust the customer has in the payment card, likely on a binary scale (0 = no trust, 1 = trust).</li>
<li>build: Indicates the perception of the card’s build quality. Coded as binary (0 = low, 1 = high).</li>
<li>differs: Reflects whether the payment card is perceived as different from others. Coded as binary (0 = no, 1 = yes).</li>
<li>easy: Assesses how easy it is to use the payment card. Coded as binary (0 = not easy, 1 = easy).</li>
<li>appealing: Indicates whether the card is visually or otherwise appealing. Coded as binary (0 = no, 1 = yes).</li>
<li>rewarding: Measures whether the card’s rewards program is satisfactory. Coded as binary (0 = no, 1 = yes).</li>
<li>popular: Indicates if the card is popular or widely accepted. Coded as binary (0 = no, 1 = yes).</li>
<li>service: Reflects the quality of customer service associated with the card. Coded as binary (0 = poor, 1 = good).</li>
<li>impact: Measures the perceived impact or influence of the card. Coded as binary (0 = low, 1 = high).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation plot</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">8</span>))</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>sns.heatmap(df.corr(), annot<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">'coolwarm'</span>, fmt<span class="op">=</span><span class="st">'.2f'</span>)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Correlation Matrix'</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="hw4_questions_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<section id="satisfaction-correlations" class="level4">
<h4 class="anchored" data-anchor-id="satisfaction-correlations">Satisfaction Correlations:</h4>
<ul>
<li>Trust: The correlation between satisfaction and trust is 0.26. This indicates a moderate positive relationship, suggesting that higher trust in the payment card is associated with higher customer satisfaction.</li>
<li>Build: The correlation between satisfaction and build is 0.19. This suggests a weak positive relationship, indicating that customers who perceive the card as well-built tend to have higher satisfaction.</li>
<li>Differs: The correlation between satisfaction and differs is 0.18. This also indicates a weak positive relationship, meaning that customers who find the card different from others tend to be more satisfied.</li>
<li>Easy: The correlation between satisfaction and easy is 0.21, showing a weak positive relationship. Customers who find the card easy to use are generally more satisfied.</li>
<li>Appealing: The correlation between satisfaction and appealing is 0.21, which is a weak positive relationship. This suggests that customers who find the card appealing tend to be more satisfied.</li>
<li>Rewarding: The correlation between satisfaction and rewarding is 0.19, indicating a weak positive relationship. Customers who find the card rewarding are slightly more satisfied.</li>
<li>Popular: The correlation between satisfaction and popular is 0.17, showing a weak positive relationship, suggesting that more popular cards slightly correlate with higher satisfaction.</li>
<li>Service: The correlation between satisfaction and service is 0.25, indicating a moderate positive relationship. Good service is an important factor in customer satisfaction.</li>
<li>Impact: The correlation between satisfaction and impact is 0.25, also indicating a moderate positive relationship. This suggests that the perceived impact of the card on the user’s life correlates with their satisfaction.</li>
</ul>
</section>
<section id="inter-correlations-between-predictors" class="level4">
<h4 class="anchored" data-anchor-id="inter-correlations-between-predictors">Inter-correlations Between Predictors:</h4>
<ul>
<li>Trust and Service: A high correlation (0.50) between trust and service suggests that these two variables are closely related. Customers who trust the card likely also perceive better service.</li>
<li>Easy and Appealing: The correlation between easy and appealing is 0.43, indicating that cards which are easy to use are often also considered appealing.</li>
<li>Rewarding and Appealing: There is a strong correlation (0.48) between rewarding and appealing, suggesting that if a card is rewarding, it is also perceived as appealing.</li>
</ul>
</section>
<section id="key-takeaways" class="level4">
<h4 class="anchored" data-anchor-id="key-takeaways">Key Takeaways</h4>
<ul>
<li>Moderate Correlations with Satisfaction: Trust, service, and impact have the highest correlations with satisfaction, indicating these are key drivers.</li>
<li>Weak but Positive Correlations: Build, differs, easy, appealing, rewarding, and popular also influence satisfaction but to a lesser extent.</li>
<li>Inter-related Predictors: Several predictors are strongly inter-related, which could suggest multicollinearity. This might need to be addressed in modeling efforts.</li>
</ul>
<p><br></p>
<section id="i-will-create-a-statistical-summary-table-this-involves-calculating-pearson-correlations-standardized-regression-coefficients-and-assessing-usefulness-metrics-such-as-shapley-values-for-a-linear-regression-johnsons-relative-weights-and-the-mean-decrease-in-the-gini-coefficient-from-a-random-forest-analysis." class="level5">
<h5 class="anchored" data-anchor-id="i-will-create-a-statistical-summary-table-this-involves-calculating-pearson-correlations-standardized-regression-coefficients-and-assessing-usefulness-metrics-such-as-shapley-values-for-a-linear-regression-johnsons-relative-weights-and-the-mean-decrease-in-the-gini-coefficient-from-a-random-forest-analysis.">I will create a statistical summary table, this involves calculating Pearson correlations, standardized regression coefficients, and assessing “usefulness” metrics such as Shapley values for a linear regression, Johnson’s relative weights, and the mean decrease in the Gini coefficient from a Random Forest analysis.</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>column_order <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"brand"</span>, <span class="st">"build"</span>, <span class="st">"differs"</span>, <span class="st">"easy"</span>, <span class="st">"appealing"</span>, <span class="st">"rewarding"</span>, <span class="st">"popular"</span>, <span class="st">"service"</span>, <span class="st">"impact"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
<section id="what-is-pearson-correlations" class="level3">
<h3 class="anchored" data-anchor-id="what-is-pearson-correlations">What is Pearson Correlations?</h3>
<p>Pearson correlation measures the linear relationship between two variables. It provides a value between -1 and 1, where: - 1 indicates a perfect positive linear relationship. - -1 indicates a perfect negative linear relationship. - 0 indicates no linear relationship.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pearson Correlations</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>pearson_corr <span class="ot">&lt;-</span> <span class="fu">cor</span>(df)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>pearson_corr_satisfaction <span class="ot">&lt;-</span> pearson_corr[, <span class="st">"satisfaction"</span>]</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>pearson_corr_satisfaction <span class="ot">&lt;-</span> pearson_corr_satisfaction[<span class="fu">names</span>(pearson_corr_satisfaction) <span class="sc">!=</span> <span class="st">"satisfaction"</span>]</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>pearson_corr_satisfaction <span class="ot">&lt;-</span> pearson_corr_satisfaction[column_order]</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>pearson_corr_satisfaction </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      brand       build     differs        easy   appealing   rewarding 
-0.04929602  0.19189575  0.18480093  0.21298469  0.20799652  0.19456145 
    popular     service      impact 
 0.17142528  0.25109823  0.25453855 </code></pre>
</div>
</div>
<section id="pearson-correlation-results-explained" class="level4">
<h4 class="anchored" data-anchor-id="pearson-correlation-results-explained">Pearson Correlation Results Explained</h4>
<ul>
<li><p>brand (-0.0493): This indicates a very weak negative linear relationship between the brand of the payment card and customer satisfaction. Essentially, the brand has almost no impact on satisfaction in a linear context.</p></li>
<li><p>build (0.1919): There is a positive correlation between the perceived build quality of the payment card and customer satisfaction. This suggests that as the build quality improves, customer satisfaction tends to increase, though the relationship is moderate.</p></li>
<li><p>differs (0.1848): This shows a positive correlation between how different the payment card is perceived to be from other cards and customer satisfaction. A unique or differentiated card tends to lead to higher satisfaction.</p></li>
<li><p>easy (0.2130): This positive correlation indicates that ease of use is moderately associated with higher customer satisfaction. Customers are more satisfied when the card is easy to use.</p></li>
<li><p>appealing (0.2080): The visual or overall appeal of the payment card has a moderate positive impact on customer satisfaction. More appealing cards tend to result in higher satisfaction.</p></li>
<li><p>rewarding (0.1946): This positive correlation suggests that a rewarding payment card (e.g., one that offers benefits and rewards) is associated with higher customer satisfaction.</p></li>
<li><p>popular (0.1714): The popularity of the payment card has a positive but relatively weaker correlation with customer satisfaction. More popular cards tend to have higher satisfaction, but the effect is less pronounced compared to other features.</p></li>
<li><p>service (0.2511): This indicates a moderate to strong positive correlation between the quality of customer service and satisfaction. Good customer service is strongly associated with higher customer satisfaction.</p></li>
<li><p>impact (0.2545): The perceived impact of the card has the strongest positive correlation with customer satisfaction among the variables listed. Cards that customers feel make a significant impact in their lives tend to have much higher satisfaction.</p></li>
</ul>
<p>In summary, service and impact are the most influential factors, followed by ease of use and appealing features. Brand has the least impact on customer satisfaction in this context.</p>
<p><br></p>
</section>
</section>
<section id="what-is-multiple-regression-coefficients" class="level3">
<h3 class="anchored" data-anchor-id="what-is-multiple-regression-coefficients">What is Multiple Regression Coefficients?</h3>
<p>Multiple regression coefficients represent the relationship between each independent variable (feature) and the dependent variable (customer satisfaction) while holding all other variables constant. In other words, they show the unique contribution of each feature to customer satisfaction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Standardize the predictor variables and the dependent variable</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>df_scaled <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="sc">-</span>satisfaction, scale)) </span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the linear model with standardized predictors</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(satisfaction <span class="sc">~</span> ., <span class="at">data =</span> df_scaled)</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the standardized coefficients</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>standardized_coeffs <span class="ot">&lt;-</span> <span class="fu">summary</span>(model)<span class="sc">$</span>coefficients[<span class="sc">-</span><span class="dv">1</span>, <span class="st">"Estimate"</span>]</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>standardized_coeffs <span class="ot">&lt;-</span> standardized_coeffs[column_order]</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>standardized_coeffs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     brand      build    differs       easy  appealing  rewarding    popular 
0.01216632 0.02256820 0.03326360 0.02650449 0.04111114 0.00709324 0.02035154 
   service     impact 
0.10288677 0.15160538 </code></pre>
</div>
</div>
<section id="multiple-regression-coefficients-explained" class="level4">
<h4 class="anchored" data-anchor-id="multiple-regression-coefficients-explained">Multiple Regression Coefficients Explained</h4>
<ul>
<li><p>brand (0.0122): The brand of the payment card has a very small positive impact on customer satisfaction. This suggests that while brand matters, its influence on satisfaction is minimal.</p></li>
<li><p>build (0.0226): The build quality has a small positive impact on customer satisfaction. Better build quality contributes to higher satisfaction, but the effect is modest.</p></li>
<li><p>differs (0.0333): The uniqueness or differentiation of the card has a moderate positive impact on customer satisfaction. Cards perceived as different from others tend to slightly increase satisfaction.</p></li>
<li><p>easy (0.0265): Ease of use has a small to moderate positive impact on customer satisfaction. Customers appreciate cards that are easier to use.</p></li>
<li><p>appealing (0.0411): The visual or overall appeal of the card has a moderate positive impact on customer satisfaction. More appealing cards contribute more significantly to higher satisfaction.</p></li>
<li><p>rewarding (0.0071): Rewards have a very small positive impact on customer satisfaction. While rewards are beneficial, their overall impact on satisfaction is relatively minor.</p></li>
<li><p>popular (0.0204): The popularity of the card has a small positive impact on customer satisfaction. More popular cards tend to slightly increase satisfaction.</p></li>
<li><p>service (0.1029): The quality of customer service has a significant positive impact on customer satisfaction. Good customer service is one of the most influential factors in increasing satisfaction.</p></li>
<li><p>impact (0.1516): The perceived impact of the card has the largest positive impact on customer satisfaction. Cards that make a significant difference in customers’ lives lead to much higher satisfaction.</p></li>
</ul>
<p>Most Significant Drivers: “impact” (0.1516) and “service” (0.1029) are the most significant drivers of customer satisfaction.</p>
<p><br></p>
</section>
</section>
<section id="what-is-johnsons-epilon" class="level3">
<h3 class="anchored" data-anchor-id="what-is-johnsons-epilon">What is Johnson’s Epilon?</h3>
<p>Johnson’s relative weights are a method used to determine the relative importance of predictor variables in multiple regression analysis. This technique helps to partition the total explained variance (R²) of the dependent variable into contributions attributable to each predictor variable, considering both their unique contributions and their contributions shared with other predictors.</p>
<p>I’m using the “lmg” method in the “relaimpo” package here.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Relative Importance (Johnson's Relative Weights)</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>relative_weights <span class="ot">&lt;-</span> <span class="fu">calc.relimp</span>(model, <span class="at">type =</span> <span class="st">"lmg"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>rel_weights_co <span class="ot">&lt;-</span> relative_weights<span class="sc">$</span>lmg <span class="sc">*</span> <span class="dv">10</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>rel_weights_co <span class="ot">&lt;-</span> rel_weights_co[column_order]</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>rel_weights_co</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     brand      build    differs       easy  appealing  rewarding    popular 
0.00342336 0.07163072 0.07269522 0.09260610 0.09136379 0.06820223 0.05621660 
   service     impact 
0.18348956 0.23622808 </code></pre>
</div>
</div>
<section id="johnsons-relative-weights" class="level4">
<h4 class="anchored" data-anchor-id="johnsons-relative-weights">Johnson’s Relative Weights</h4>
<ul>
<li><p>brand (0.0034): The brand of the payment card has a very small impact on customer satisfaction. Its contribution to the explained variance in satisfaction is minimal.</p></li>
<li><p>build (0.0716): The build quality of the payment card has a moderate impact on customer satisfaction. It contributes significantly more than the brand, indicating that the physical quality of the card is an important factor for customers.</p></li>
<li><p>differs (0.0727): The feature indicating whether the card is perceived as different from others has a moderate impact on customer satisfaction. Customers value uniqueness, which contributes positively to their satisfaction.</p></li>
<li><p>easy (0.0926): Ease of use has a relatively high impact on customer satisfaction. This suggests that cards that are easier to use contribute significantly to higher satisfaction.</p></li>
<li><p>appealing (0.0914): The visual or overall appeal of the card also has a high impact on customer satisfaction. Customers place a strong value on the attractiveness of the card.</p></li>
<li><p>rewarding (0.0682): The rewards offered by the payment card have a moderate impact on customer satisfaction. While important, rewards are slightly less influential than ease of use and appeal.</p></li>
<li><p>popular (0.0562): The popularity of the payment card has a moderate impact on customer satisfaction. While still important, its influence is less compared to ease of use, appeal, and build quality.</p></li>
<li><p>service (0.1835): The quality of customer service has a significant impact on customer satisfaction. This indicates that good customer service is one of the most important factors in increasing satisfaction.</p></li>
<li><p>impact (0.2362): The perceived impact of the payment card has the highest relative weight, making it the most important predictor of customer satisfaction. This suggests that features of the card that significantly affect the user’s experience or lifestyle are crucial to their overall satisfaction.</p></li>
</ul>
<p>Most Significant Drivers: - Impact (0.2362): The most important factor, indicating that significant positive experiences or effects on users’ lives drive satisfaction the most. - Service (0.1835): Also highly significant, emphasizing the critical role of high-quality customer service.</p>
<p><br></p>
</section>
</section>
<section id="what-is-rf-gini-coefficient" class="level3">
<h3 class="anchored" data-anchor-id="what-is-rf-gini-coefficient">What is RF Gini Coefficient?</h3>
<p>The RF Gini coefficient, or Random Forest Gini importance, is a measure of feature importance in the context of Random Forest models. It is based on the Gini impurity, which is a metric used to evaluate the quality of splits in decision trees.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert satisfaction to a factor for classification</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>satisfaction <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df<span class="sc">$</span>satisfaction)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Random Forest for Mean Decrease in Gini</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>rf_model <span class="ot">&lt;-</span> randomForest<span class="sc">::</span><span class="fu">randomForest</span>(satisfaction <span class="sc">~</span> ., <span class="at">data =</span> df, <span class="at">importance =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>importance_values <span class="ot">&lt;-</span> randomForest<span class="sc">::</span><span class="fu">importance</span>(rf_model, <span class="at">type =</span> <span class="dv">2</span>)</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Extract the Mean Decrease in Gini values</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>mean_decrease_gini <span class="ot">&lt;-</span> importance_values[, <span class="st">"MeanDecreaseGini"</span>]</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalize the Gini importance values to percentages</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>total_importance <span class="ot">&lt;-</span> <span class="fu">sum</span>(mean_decrease_gini)</span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>importance_values_named <span class="ot">&lt;-</span> (mean_decrease_gini <span class="sc">/</span> total_importance) <span class="sc">*</span> <span class="dv">1</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>importance_values_named <span class="ot">&lt;-</span> importance_values_named[column_order]</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>importance_values_named</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     brand      build    differs       easy  appealing  rewarding    popular 
0.18836033 0.05178355 0.04675531 0.04993704 0.04901403 0.05085820 0.05748903 
   service     impact 
0.04645259 0.04515332 </code></pre>
</div>
</div>
<section id="mean-decrease-in-rf-gini-coefficient" class="level4">
<h4 class="anchored" data-anchor-id="mean-decrease-in-rf-gini-coefficient">Mean Decrease in RF Gini Coefficient</h4>
<ul>
<li><p>brand (0.1884): The brand of the payment card has the highest importance according to the RF Gini importance metric. This suggests that brand plays a significant role in predicting customer satisfaction within the context of the Random Forest model.</p></li>
<li><p>build (0.0518): The build quality of the payment card has a moderate importance. This indicates that the physical quality of the card is an important factor, but less critical compared to brand.</p></li>
<li><p>differs (0.0468): The feature indicating whether the card is perceived as different from others has moderate importance. Customers value uniqueness, but its impact is slightly less compared to build quality.</p></li>
<li><p>easy (0.0499): Ease of use has moderate importance. This suggests that how easy the card is to use contributes to customer satisfaction, but is less influential than brand.</p></li>
<li><p>appealing (0.0490): The visual or overall appeal of the card has moderate importance. While appealing features are valued, their importance is similar to ease of use.</p></li>
<li><p>rewarding (0.0509): The rewards offered by the payment card have moderate importance. Rewards are slightly more influential than ease of use and appeal in predicting customer satisfaction.</p></li>
<li><p>popular (0.0575): The popularity of the payment card has moderate importance. It is more influential than ease of use, appeal, and build quality but less critical than brand.</p></li>
<li><p>service (0.0465): The quality of customer service has moderate importance. Although customer service is crucial, its importance is slightly less than that of rewards and popularity in the context of the Random Forest model.</p></li>
<li><p>impact (0.0452): The perceived impact of the payment card has moderate importance. It is the least important feature among the ones listed, but still contributes to the overall prediction of customer satisfaction.</p></li>
</ul>
<p>Most Significant Driver: Brand (0.1884) is the most important feature in the Random Forest model, indicating that the brand of the card significantly influences customer satisfaction.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">Perception =</span> <span class="fu">c</span>(<span class="st">"Is offered by a brand I trust"</span>, <span class="st">"Helps build credit quickly"</span>, <span class="st">"Is different from other cards"</span>, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Is easy to use"</span>, <span class="st">"Has appealing benefits or rewards"</span>, <span class="st">"Rewards me for responsible usage"</span>, </span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>                 <span class="st">"Is used by a lot of people"</span>, <span class="st">"Provides outstanding customer service"</span>, <span class="st">"Makes a difference in my life"</span>),</span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Pearson_Correlations =</span> pearson_corr_satisfaction,</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Standardized_Multiple_Regression_Coefficients =</span> standardized_coeffs,</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">Johnsons_Relative_Weights =</span> rel_weights_co,</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Mean_Decrease_in_RF_Gini_Coefficient =</span> importance_values_named</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Round and convert numerical columns to percentage strings</span></span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> results <span class="sc">%&gt;%</span></span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="sc">-</span>Perception, <span class="sc">~</span> <span class="fu">round</span>(. <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>))) <span class="sc">%&gt;%</span></span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="sc">-</span>Perception, <span class="sc">~</span> <span class="fu">paste0</span>(., <span class="st">"%"</span>)))</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>gt_table <span class="ot">&lt;-</span> <span class="fu">gt</span>(results) <span class="sc">%&gt;%</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_header</span>(<span class="at">title =</span> <span class="st">"Perception Analysis"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">cols_label</span>(</span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">Perception =</span> <span class="st">"Perception"</span>,</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>    <span class="at">Pearson_Correlations =</span> <span class="fu">md</span>(<span class="st">"Pearson&lt;br&gt;Correlations"</span>),</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">Standardized_Multiple_Regression_Coefficients =</span> <span class="fu">md</span>(<span class="st">"Standardized&lt;br&gt;Multiple Regression&lt;br&gt;Coefficients"</span>),</span>
<span id="cb15-23"><a href="#cb15-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">Johnsons_Relative_Weights =</span> <span class="fu">md</span>(<span class="st">"Johnsons&lt;br&gt;Relative Weights"</span>),</span>
<span id="cb15-24"><a href="#cb15-24" aria-hidden="true" tabindex="-1"></a>    <span class="at">Mean_Decrease_in_RF_Gini_Coefficient =</span> <span class="fu">md</span>(<span class="st">"Mean Decrease in&lt;br&gt;RF Gini Coefficient"</span>)</span>
<span id="cb15-25"><a href="#cb15-25" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb15-26"><a href="#cb15-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tab_options</span>(</span>
<span id="cb15-27"><a href="#cb15-27" aria-hidden="true" tabindex="-1"></a>    <span class="at">table.font.size =</span> <span class="st">'small'</span>,</span>
<span id="cb15-28"><a href="#cb15-28" aria-hidden="true" tabindex="-1"></a>    <span class="at">data_row.padding =</span> <span class="fu">px</span>(<span class="dv">3</span>)</span>
<span id="cb15-29"><a href="#cb15-29" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb15-30"><a href="#cb15-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-31"><a href="#cb15-31" aria-hidden="true" tabindex="-1"></a>gt_table</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div id="ujkmihcoww" style="padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>#ujkmihcoww table {
  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

#ujkmihcoww thead, #ujkmihcoww tbody, #ujkmihcoww tfoot, #ujkmihcoww tr, #ujkmihcoww td, #ujkmihcoww th {
  border-style: none;
}

#ujkmihcoww p {
  margin: 0;
  padding: 0;
}

#ujkmihcoww .gt_table {
  display: table;
  border-collapse: collapse;
  line-height: normal;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: small;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#ujkmihcoww .gt_caption {
  padding-top: 4px;
  padding-bottom: 4px;
}

#ujkmihcoww .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#ujkmihcoww .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 3px;
  padding-bottom: 5px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#ujkmihcoww .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ujkmihcoww .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ujkmihcoww .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#ujkmihcoww .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#ujkmihcoww .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#ujkmihcoww .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#ujkmihcoww .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#ujkmihcoww .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#ujkmihcoww .gt_spanner_row {
  border-bottom-style: hidden;
}

#ujkmihcoww .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  text-align: left;
}

#ujkmihcoww .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#ujkmihcoww .gt_from_md > :first-child {
  margin-top: 0;
}

#ujkmihcoww .gt_from_md > :last-child {
  margin-bottom: 0;
}

#ujkmihcoww .gt_row {
  padding-top: 3px;
  padding-bottom: 3px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#ujkmihcoww .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#ujkmihcoww .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#ujkmihcoww .gt_row_group_first td {
  border-top-width: 2px;
}

#ujkmihcoww .gt_row_group_first th {
  border-top-width: 2px;
}

#ujkmihcoww .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ujkmihcoww .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#ujkmihcoww .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#ujkmihcoww .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ujkmihcoww .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#ujkmihcoww .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#ujkmihcoww .gt_last_grand_summary_row_top {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: double;
  border-bottom-width: 6px;
  border-bottom-color: #D3D3D3;
}

#ujkmihcoww .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#ujkmihcoww .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#ujkmihcoww .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ujkmihcoww .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ujkmihcoww .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#ujkmihcoww .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#ujkmihcoww .gt_left {
  text-align: left;
}

#ujkmihcoww .gt_center {
  text-align: center;
}

#ujkmihcoww .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#ujkmihcoww .gt_font_normal {
  font-weight: normal;
}

#ujkmihcoww .gt_font_bold {
  font-weight: bold;
}

#ujkmihcoww .gt_font_italic {
  font-style: italic;
}

#ujkmihcoww .gt_super {
  font-size: 65%;
}

#ujkmihcoww .gt_footnote_marks {
  font-size: 75%;
  vertical-align: 0.4em;
  position: initial;
}

#ujkmihcoww .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#ujkmihcoww .gt_indent_1 {
  text-indent: 5px;
}

#ujkmihcoww .gt_indent_2 {
  text-indent: 10px;
}

#ujkmihcoww .gt_indent_3 {
  text-indent: 15px;
}

#ujkmihcoww .gt_indent_4 {
  text-indent: 20px;
}

#ujkmihcoww .gt_indent_5 {
  text-indent: 25px;
}
</style>

<table class="gt_table table table-sm table-striped small" data-quarto-postprocess="true" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header gt_heading">
<th colspan="5" class="gt_heading gt_title gt_font_normal gt_bottom_border">Perception Analysis</th>
</tr>
<tr class="odd gt_col_headings">
<th id="Perception" class="gt_col_heading gt_columns_bottom_border gt_left" data-quarto-table-cell-role="th" scope="col">Perception</th>
<th id="Pearson<br>Correlations" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Pearson<br>
Correlations</th>
<th id="Standardized<br>Multiple Regression<br>Coefficients" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Standardized<br>
Multiple Regression<br>
Coefficients</th>
<th id="Johnsons<br>Relative Weights" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Johnsons<br>
Relative Weights</th>
<th id="Mean Decrease in<br>RF Gini Coefficient" class="gt_col_heading gt_columns_bottom_border gt_right" data-quarto-table-cell-role="th" scope="col">Mean Decrease in<br>
RF Gini Coefficient</th>
</tr>
</thead>
<tbody class="gt_table_body">
<tr class="odd">
<td class="gt_row gt_left" headers="Perception">Is offered by a brand I trust</td>
<td class="gt_row gt_right" headers="Pearson_Correlations">-4.9%</td>
<td class="gt_row gt_right" headers="Standardized_Multiple_Regression_Coefficients">1.2%</td>
<td class="gt_row gt_right" headers="Johnsons_Relative_Weights">0.3%</td>
<td class="gt_row gt_right" headers="Mean_Decrease_in_RF_Gini_Coefficient">18.8%</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Perception">Helps build credit quickly</td>
<td class="gt_row gt_right" headers="Pearson_Correlations">19.2%</td>
<td class="gt_row gt_right" headers="Standardized_Multiple_Regression_Coefficients">2.3%</td>
<td class="gt_row gt_right" headers="Johnsons_Relative_Weights">7.2%</td>
<td class="gt_row gt_right" headers="Mean_Decrease_in_RF_Gini_Coefficient">5.2%</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Perception">Is different from other cards</td>
<td class="gt_row gt_right" headers="Pearson_Correlations">18.5%</td>
<td class="gt_row gt_right" headers="Standardized_Multiple_Regression_Coefficients">3.3%</td>
<td class="gt_row gt_right" headers="Johnsons_Relative_Weights">7.3%</td>
<td class="gt_row gt_right" headers="Mean_Decrease_in_RF_Gini_Coefficient">4.7%</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Perception">Is easy to use</td>
<td class="gt_row gt_right" headers="Pearson_Correlations">21.3%</td>
<td class="gt_row gt_right" headers="Standardized_Multiple_Regression_Coefficients">2.7%</td>
<td class="gt_row gt_right" headers="Johnsons_Relative_Weights">9.3%</td>
<td class="gt_row gt_right" headers="Mean_Decrease_in_RF_Gini_Coefficient">5%</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Perception">Has appealing benefits or rewards</td>
<td class="gt_row gt_right" headers="Pearson_Correlations">20.8%</td>
<td class="gt_row gt_right" headers="Standardized_Multiple_Regression_Coefficients">4.1%</td>
<td class="gt_row gt_right" headers="Johnsons_Relative_Weights">9.1%</td>
<td class="gt_row gt_right" headers="Mean_Decrease_in_RF_Gini_Coefficient">4.9%</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Perception">Rewards me for responsible usage</td>
<td class="gt_row gt_right" headers="Pearson_Correlations">19.5%</td>
<td class="gt_row gt_right" headers="Standardized_Multiple_Regression_Coefficients">0.7%</td>
<td class="gt_row gt_right" headers="Johnsons_Relative_Weights">6.8%</td>
<td class="gt_row gt_right" headers="Mean_Decrease_in_RF_Gini_Coefficient">5.1%</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Perception">Is used by a lot of people</td>
<td class="gt_row gt_right" headers="Pearson_Correlations">17.1%</td>
<td class="gt_row gt_right" headers="Standardized_Multiple_Regression_Coefficients">2%</td>
<td class="gt_row gt_right" headers="Johnsons_Relative_Weights">5.6%</td>
<td class="gt_row gt_right" headers="Mean_Decrease_in_RF_Gini_Coefficient">5.7%</td>
</tr>
<tr class="even">
<td class="gt_row gt_left" headers="Perception">Provides outstanding customer service</td>
<td class="gt_row gt_right" headers="Pearson_Correlations">25.1%</td>
<td class="gt_row gt_right" headers="Standardized_Multiple_Regression_Coefficients">10.3%</td>
<td class="gt_row gt_right" headers="Johnsons_Relative_Weights">18.3%</td>
<td class="gt_row gt_right" headers="Mean_Decrease_in_RF_Gini_Coefficient">4.6%</td>
</tr>
<tr class="odd">
<td class="gt_row gt_left" headers="Perception">Makes a difference in my life</td>
<td class="gt_row gt_right" headers="Pearson_Correlations">25.5%</td>
<td class="gt_row gt_right" headers="Standardized_Multiple_Regression_Coefficients">15.2%</td>
<td class="gt_row gt_right" headers="Johnsons_Relative_Weights">23.6%</td>
<td class="gt_row gt_right" headers="Mean_Decrease_in_RF_Gini_Coefficient">4.5%</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<section id="i-will-rank-the-variables-by-importance-by-scoring-and-considering-all-the-metrics-previously-mentioned-pearson-correlations-standardized-regression-coefficients-johnsons-relative-weights-and-the-mean-decrease-in-the-gini-coefficient-from-a-random-forest.-each-metric-will-be-evaluated-and-combined-to-provide-a-comprehensive-ranking-of-the-variables-based-on-their-overall-contribution-and-impact-on-the-model.-this-ranking-will-help-in-understanding-which-variables-are-most-influential-in-predicting-the-outcome." class="level5">
<h5 class="anchored" data-anchor-id="i-will-rank-the-variables-by-importance-by-scoring-and-considering-all-the-metrics-previously-mentioned-pearson-correlations-standardized-regression-coefficients-johnsons-relative-weights-and-the-mean-decrease-in-the-gini-coefficient-from-a-random-forest.-each-metric-will-be-evaluated-and-combined-to-provide-a-comprehensive-ranking-of-the-variables-based-on-their-overall-contribution-and-impact-on-the-model.-this-ranking-will-help-in-understanding-which-variables-are-most-influential-in-predicting-the-outcome.">I will rank the variables by importance by scoring and considering all the metrics previously mentioned: Pearson correlations, standardized regression coefficients, Johnson’s relative weights, and the mean decrease in the Gini coefficient from a Random Forest. Each metric will be evaluated and combined to provide a comprehensive ranking of the variables based on their overall contribution and impact on the model. This ranking will help in understanding which variables are most influential in predicting the outcome.</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Input the importance values from the table</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>importance_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variables =</span> column_order,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">Pearson =</span> pearson_corr_satisfaction,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">Standardized_Coefficients =</span> standardized_coeffs,</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">Johnsons_Weights =</span> rel_weights_co,</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">RF_Gini =</span> importance_values_named</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>importance_data <span class="sc">%&gt;%</span> </span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 30%">
<col style="width: 20%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Variables</th>
<th style="text-align: right;">Pearson</th>
<th style="text-align: right;">Standardized_Coefficients</th>
<th style="text-align: right;">Johnsons_Weights</th>
<th style="text-align: right;">RF_Gini</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">brand</td>
<td style="text-align: left;">brand</td>
<td style="text-align: right;">-0.0492960</td>
<td style="text-align: right;">0.0121663</td>
<td style="text-align: right;">0.0034234</td>
<td style="text-align: right;">0.1883603</td>
</tr>
<tr class="even">
<td style="text-align: left;">build</td>
<td style="text-align: left;">build</td>
<td style="text-align: right;">0.1918957</td>
<td style="text-align: right;">0.0225682</td>
<td style="text-align: right;">0.0716307</td>
<td style="text-align: right;">0.0517836</td>
</tr>
<tr class="odd">
<td style="text-align: left;">differs</td>
<td style="text-align: left;">differs</td>
<td style="text-align: right;">0.1848009</td>
<td style="text-align: right;">0.0332636</td>
<td style="text-align: right;">0.0726952</td>
<td style="text-align: right;">0.0467553</td>
</tr>
<tr class="even">
<td style="text-align: left;">easy</td>
<td style="text-align: left;">easy</td>
<td style="text-align: right;">0.2129847</td>
<td style="text-align: right;">0.0265045</td>
<td style="text-align: right;">0.0926061</td>
<td style="text-align: right;">0.0499370</td>
</tr>
<tr class="odd">
<td style="text-align: left;">appealing</td>
<td style="text-align: left;">appealing</td>
<td style="text-align: right;">0.2079965</td>
<td style="text-align: right;">0.0411111</td>
<td style="text-align: right;">0.0913638</td>
<td style="text-align: right;">0.0490140</td>
</tr>
<tr class="even">
<td style="text-align: left;">rewarding</td>
<td style="text-align: left;">rewarding</td>
<td style="text-align: right;">0.1945615</td>
<td style="text-align: right;">0.0070932</td>
<td style="text-align: right;">0.0682022</td>
<td style="text-align: right;">0.0508582</td>
</tr>
<tr class="odd">
<td style="text-align: left;">popular</td>
<td style="text-align: left;">popular</td>
<td style="text-align: right;">0.1714253</td>
<td style="text-align: right;">0.0203515</td>
<td style="text-align: right;">0.0562166</td>
<td style="text-align: right;">0.0574890</td>
</tr>
<tr class="even">
<td style="text-align: left;">service</td>
<td style="text-align: left;">service</td>
<td style="text-align: right;">0.2510982</td>
<td style="text-align: right;">0.1028868</td>
<td style="text-align: right;">0.1834896</td>
<td style="text-align: right;">0.0464526</td>
</tr>
<tr class="odd">
<td style="text-align: left;">impact</td>
<td style="text-align: left;">impact</td>
<td style="text-align: right;">0.2545386</td>
<td style="text-align: right;">0.1516054</td>
<td style="text-align: right;">0.2362281</td>
<td style="text-align: right;">0.0451533</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalize the scores (convert Pearson to absolute values for normalization)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>importance_data_normalized <span class="ot">&lt;-</span> importance_data <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">Pearson =</span> <span class="fu">abs</span>(Pearson),</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">Pearson =</span> Pearson <span class="sc">/</span> <span class="fu">sum</span>(Pearson) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">Standardized_Coefficients =</span> Standardized_Coefficients <span class="sc">/</span> <span class="fu">sum</span>(Standardized_Coefficients) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Johnsons_Weights =</span> Johnsons_Weights <span class="sc">/</span> <span class="fu">sum</span>(Johnsons_Weights) <span class="sc">*</span> <span class="dv">100</span>,</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">RF_Gini =</span> RF_Gini <span class="sc">/</span> <span class="fu">sum</span>(RF_Gini) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>importance_data_normalized <span class="sc">%&gt;%</span> </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 31%">
<col style="width: 20%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Variables</th>
<th style="text-align: right;">Pearson</th>
<th style="text-align: right;">Standardized_Coefficients</th>
<th style="text-align: right;">Johnsons_Weights</th>
<th style="text-align: right;">RF_Gini</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">brand</td>
<td style="text-align: left;">brand</td>
<td style="text-align: right;">2.868387</td>
<td style="text-align: right;">2.913735</td>
<td style="text-align: right;">0.3908589</td>
<td style="text-align: right;">32.154188</td>
</tr>
<tr class="even">
<td style="text-align: left;">build</td>
<td style="text-align: left;">build</td>
<td style="text-align: right;">11.165835</td>
<td style="text-align: right;">5.404900</td>
<td style="text-align: right;">8.1783704</td>
<td style="text-align: right;">8.839749</td>
</tr>
<tr class="odd">
<td style="text-align: left;">differs</td>
<td style="text-align: left;">differs</td>
<td style="text-align: right;">10.753008</td>
<td style="text-align: right;">7.966363</td>
<td style="text-align: right;">8.2999088</td>
<td style="text-align: right;">7.981399</td>
</tr>
<tr class="even">
<td style="text-align: left;">easy</td>
<td style="text-align: left;">easy</td>
<td style="text-align: right;">12.392937</td>
<td style="text-align: right;">6.347611</td>
<td style="text-align: right;">10.5732147</td>
<td style="text-align: right;">8.524539</td>
</tr>
<tr class="odd">
<td style="text-align: left;">appealing</td>
<td style="text-align: left;">appealing</td>
<td style="text-align: right;">12.102690</td>
<td style="text-align: right;">9.845785</td>
<td style="text-align: right;">10.4313755</td>
<td style="text-align: right;">8.366976</td>
</tr>
<tr class="even">
<td style="text-align: left;">rewarding</td>
<td style="text-align: left;">rewarding</td>
<td style="text-align: right;">11.320944</td>
<td style="text-align: right;">1.698773</td>
<td style="text-align: right;">7.7869260</td>
<td style="text-align: right;">8.681787</td>
</tr>
<tr class="odd">
<td style="text-align: left;">popular</td>
<td style="text-align: left;">popular</td>
<td style="text-align: right;">9.974720</td>
<td style="text-align: right;">4.874030</td>
<td style="text-align: right;">6.4184780</td>
<td style="text-align: right;">9.813707</td>
</tr>
<tr class="even">
<td style="text-align: left;">service</td>
<td style="text-align: left;">service</td>
<td style="text-align: right;">14.610649</td>
<td style="text-align: right;">24.640546</td>
<td style="text-align: right;">20.9497480</td>
<td style="text-align: right;">7.929723</td>
</tr>
<tr class="odd">
<td style="text-align: left;">impact</td>
<td style="text-align: left;">impact</td>
<td style="text-align: right;">14.810830</td>
<td style="text-align: right;">36.308257</td>
<td style="text-align: right;">26.9711198</td>
<td style="text-align: right;">7.707931</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the composite scores</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>importance_data_normalized <span class="ot">&lt;-</span> importance_data_normalized <span class="sc">%&gt;%</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Composite_Score =</span> <span class="fu">mean</span>(<span class="fu">c</span>(Pearson, Standardized_Coefficients, Johnsons_Weights, RF_Gini)))</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>importance_data_normalized <span class="sc">%&gt;%</span> </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 29%">
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variables</th>
<th style="text-align: right;">Pearson</th>
<th style="text-align: right;">Standardized_Coefficients</th>
<th style="text-align: right;">Johnsons_Weights</th>
<th style="text-align: right;">RF_Gini</th>
<th style="text-align: right;">Composite_Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">brand</td>
<td style="text-align: right;">2.868387</td>
<td style="text-align: right;">2.913735</td>
<td style="text-align: right;">0.3908589</td>
<td style="text-align: right;">32.154188</td>
<td style="text-align: right;">9.581792</td>
</tr>
<tr class="even">
<td style="text-align: left;">build</td>
<td style="text-align: right;">11.165835</td>
<td style="text-align: right;">5.404900</td>
<td style="text-align: right;">8.1783704</td>
<td style="text-align: right;">8.839749</td>
<td style="text-align: right;">8.397214</td>
</tr>
<tr class="odd">
<td style="text-align: left;">differs</td>
<td style="text-align: right;">10.753008</td>
<td style="text-align: right;">7.966363</td>
<td style="text-align: right;">8.2999088</td>
<td style="text-align: right;">7.981399</td>
<td style="text-align: right;">8.750170</td>
</tr>
<tr class="even">
<td style="text-align: left;">easy</td>
<td style="text-align: right;">12.392937</td>
<td style="text-align: right;">6.347611</td>
<td style="text-align: right;">10.5732147</td>
<td style="text-align: right;">8.524539</td>
<td style="text-align: right;">9.459575</td>
</tr>
<tr class="odd">
<td style="text-align: left;">appealing</td>
<td style="text-align: right;">12.102690</td>
<td style="text-align: right;">9.845785</td>
<td style="text-align: right;">10.4313755</td>
<td style="text-align: right;">8.366976</td>
<td style="text-align: right;">10.186707</td>
</tr>
<tr class="even">
<td style="text-align: left;">rewarding</td>
<td style="text-align: right;">11.320944</td>
<td style="text-align: right;">1.698773</td>
<td style="text-align: right;">7.7869260</td>
<td style="text-align: right;">8.681787</td>
<td style="text-align: right;">7.372108</td>
</tr>
<tr class="odd">
<td style="text-align: left;">popular</td>
<td style="text-align: right;">9.974720</td>
<td style="text-align: right;">4.874030</td>
<td style="text-align: right;">6.4184780</td>
<td style="text-align: right;">9.813707</td>
<td style="text-align: right;">7.770234</td>
</tr>
<tr class="even">
<td style="text-align: left;">service</td>
<td style="text-align: right;">14.610649</td>
<td style="text-align: right;">24.640546</td>
<td style="text-align: right;">20.9497480</td>
<td style="text-align: right;">7.929723</td>
<td style="text-align: right;">17.032666</td>
</tr>
<tr class="odd">
<td style="text-align: left;">impact</td>
<td style="text-align: right;">14.810830</td>
<td style="text-align: right;">36.308257</td>
<td style="text-align: right;">26.9711198</td>
<td style="text-align: right;">7.707931</td>
<td style="text-align: right;">21.449535</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Rank the variables based on composite scores</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>importance_data_ranked <span class="ot">&lt;-</span> importance_data_normalized <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(<span class="fu">desc</span>(Composite_Score)) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Variables, Composite_Score) </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>importance_data_ranked <span class="sc">%&gt;%</span> </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>  knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variables</th>
<th style="text-align: right;">Composite_Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">impact</td>
<td style="text-align: right;">21.449535</td>
</tr>
<tr class="even">
<td style="text-align: left;">service</td>
<td style="text-align: right;">17.032666</td>
</tr>
<tr class="odd">
<td style="text-align: left;">appealing</td>
<td style="text-align: right;">10.186707</td>
</tr>
<tr class="even">
<td style="text-align: left;">brand</td>
<td style="text-align: right;">9.581792</td>
</tr>
<tr class="odd">
<td style="text-align: left;">easy</td>
<td style="text-align: right;">9.459575</td>
</tr>
<tr class="even">
<td style="text-align: left;">differs</td>
<td style="text-align: right;">8.750170</td>
</tr>
<tr class="odd">
<td style="text-align: left;">build</td>
<td style="text-align: right;">8.397214</td>
</tr>
<tr class="even">
<td style="text-align: left;">popular</td>
<td style="text-align: right;">7.770234</td>
</tr>
<tr class="odd">
<td style="text-align: left;">rewarding</td>
<td style="text-align: right;">7.372108</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
</section>
<section id="conclusion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion">Conclusion</h3>
<p>From this variable analysis, it is clear that certain features have a more substantial impact on customer satisfaction than others.</p>
<ul>
<li><p>Focus on Impact and Service: The features “Makes a difference in my life” and “Provides outstanding customer service” are the most influential drivers of customer satisfaction. Efforts to improve these areas will likely yield the most significant improvements in customer satisfaction.</p></li>
<li><p>Enhance Appeal and Usability: Features related to appealing benefits and ease of use are also critical. Ensuring that the payment card offers attractive rewards and is user-friendly can significantly enhance customer satisfaction.</p></li>
<li><p>Brand Trust: Trust in the brand is important but not the most critical factor. Building a trustworthy brand should still be a priority, but not at the expense of improving impact, service, and usability.</p></li>
<li><p>Differentiation and Credit Building: Emphasizing unique features that differentiate the card from others and highlighting benefits related to building credit can also positively influence customer satisfaction.</p></li>
<li><p>Moderate Importance of Popularity and Rewards for Usage: While popularity and rewards for responsible usage are important, they are not as influential as other factors. These should be considered but may not require as much focus as impact, service, and appeal.</p></li>
</ul>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    const typesetMath = (el) => {
      if (window.MathJax) {
        // MathJax Typeset
        window.MathJax.typeset([el]);
      } else if (window.katex) {
        // KaTeX Render
        var mathElements = el.getElementsByClassName("math");
        var macros = [];
        for (var i = 0; i < mathElements.length; i++) {
          var texText = mathElements[i].firstChild;
          if (mathElements[i].tagName == "SPAN") {
            window.katex.render(texText.data, mathElements[i], {
              displayMode: mathElements[i].classList.contains('display'),
              throwOnError: false,
              macros: macros,
              fleqn: false
            });
          }
        }
      }
    }
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        typesetMath(container);
        return container.innerHTML
      } else {
        typesetMath(note);
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      typesetMath(note);
      return note.innerHTML;
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>